#!/bin/bash
borrado=$1

#subir archivos ---> por defecto
sudo git init
sudo git add .
sudo git commit -m 'scripts'
sudo git remote add origin https://github.com/diskxrdia/myownscripts
sudo git push -u origin master

if [ $borrado == 1 ] ; then
#elimina archivos
	usuario=$(whoami)

	if [ -d /home/$usuario/repo.back ]
	then
		cp * /home/$usuario/repo.back
	else
		mkdir /home/$usuario/repo.back
		cp * /home/$usuario/repo.back
	fi

fi
read archivo

sudo git rm $archivo
sudo git commit -m 'file deleted'
sudo git push
