#!/bin/bash
borrado=$1

gitDelete(){ #borrar archivos
	read archivo
	sudo git rm $archivo
	sudo git commit -m 'file deleted'
	sudo git push
}

gitUpload(){ #subir archivos
	sudo git init
	sudo git add .
	sudo git commit -m 'scripts'
	sudo git remote add origin https://github.com/diskxrdia/myownscripts
	sudo git push -u origin master
}

repoBackup(){ #crea backup del repositorio actual
	usuario=$(whoami)
	if [ -d /home/$usuario/repo.back ]
	then
		cp * /home/$usuario/repo.back
	else
		mkdir /home/$usuario/repo.back
		cp * /home/$usuario/repo.back
	fi
}

if [ $borrado == 0 ] ; then
	gitUpload
fi

if [ $borrado == 1 ] ; then
	repoBackup
	gitDelete
fi
