#!/bin/bash

ficher=$1

git init
git add . $fichero
git commit -m "$fichero"
git config --global user.email "antonio.aranda.luz@gmail.com"
git remote add $fichero https://github.com/diskxrdia/myownscripts
git push $fichero master
git pull $fichero master
